version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    networks:
      - symfony
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html:cached
    networks:
      - symfony
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'ecp'
    volumes:
      - persistent:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - symfony
networks:
  symfony:
    driver: bridge
volumes:
  persistent: {}
